import { BentoItem } from "@/components/BentoCard";

export const mockBentoItems: BentoItem[] = [
    {
        id: "1",
        name: "The Big Kahuna Combo",
        description: "Our signature plate with Kalua Pork, BBQ Chicken, and a scoop of Mac Salad. Served with two scoops of rice.",
        price: 18.95,
        image: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?auto=format&fit=crop&q=80&w=1000",
        tags: ["Best Seller", "Combo"],
        isBestSeller: true,
    },
    {
        id: "2",
        name: "Spam Musubi Trio",
        description: "Three pieces of our famous Spam Musubi. Glazed with our house-made teriyaki sauce.",
        price: 8.50,
        image: "https://images.unsplash.com/photo-1625244626158-b61596541736?auto=format&fit=crop&q=80&w=800",
        tags: ["Snack", "Popular"],
    },
    {
        id: "3",
        name: "Ahi Poke Bowl",
        description: "Fresh Ahi tuna tossed in shoyu, sesame oil, and onions. Served over sushi rice.",
        price: 16.95,
        image: "https://images.unsplash.com/photo-1542355727-152e79f6973c?auto=format&fit=crop&q=80&w=800",
        tags: ["Fresh", "Seafood"],
    },
    {
        id: "4",
        name: "Guava Nectar",
        description: "Ice cold, sweet and refreshing guava nectar. The perfect island drink.",
        price: 3.50,
        image: "https://images.unsplash.com/photo-1546173159-315724a31696?auto=format&fit=crop&q=80&w=800",
        tags: ["Drink"],
    },
    {
        id: "5",
        name: "Loco Moco",
        description: "Hamburger patty, fried egg, and brown gravy over rice. A comfort food classic.",
        price: 15.95,
        image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&q=80&w=800",
        tags: ["Classic"],
    },
    {
        id: "6",
        name: "Malasadas (Dozen)",
        description: "Portuguese donuts dusted in sugar. Crispy on the outside, fluffy on the inside.",
        price: 12.00,
        image: "https://images.unsplash.com/photo-1516746924755-c47509924a23?auto=format&fit=crop&q=80&w=800",
        tags: ["Dessert", "Sweet"],
    },
    {
        id: "7",
        name: "Garlic Shrimp Plate",
        description: "North Shore style garlic shrimp served with rice and lemon wedges.",
        price: 17.95,
        image: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?auto=format&fit=crop&q=80&w=800",
        tags: ["Seafood", "Spicy"],
    },
];
